# Generated by Django 5.0.7 on 2026-06-25 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_alter_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.CharField(max_length=100, unique=True)),
                ('flw_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('virtual_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('virtual_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
