# Generated by Django 5.0.7 on 2026-07-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
        ('users', '0004_user_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tutors.tutor'),
        ),
    ]
