# Generated by Django 5.0.7 on 2026-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_assigned_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
