# Generated by Django 5.0.7 on 2026-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_guardian_email_user_guardian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
