# Generated by Django 6.0.6 on 2026-06-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('courses', '0003_location_course_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.location'),
        ),
    ]
