# Generated by Django 5.0.7 on 2026-07-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_id'),
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cohorts.cohort'),
        ),
    ]
