# Generated by Django 5.0.7 on 2026-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expelled', 'Expelled'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
