# Generated by Django 5.0.7 on 2026-07-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('courses_of_instruction', models.JSONField(blank=True, default=list)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('performance_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tutor_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohorts', models.ManyToManyField(blank=True, related_name='tutors', to='cohorts.cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
