# Generated by Django 5.0.7 on 2026-07-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('courses', '0004_alter_course_options_course_order_alter_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final Assessment'), ('project', 'Project Assessment')], default='project', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('pass_mark', models.PositiveIntegerField(default=50)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='cohorts.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('cohort', 'course', 'title')},
            },
        ),
    ]
