# Generated by Django 6.0.6 on 2026-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('vocational', 'Vocational')], max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='courses/')),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('skills', models.JSONField(default=list)),
                ('outcomes', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('modules', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
