from django.core.management.base import BaseCommand
from courses.models import Course


class Command(BaseCommand):
    help = 'Seed all courses into the database'

    def handle(self, *args, **kwargs):
        courses = [
            {
                "slug": "full-stack-ai",
                "title": "Full-stack Web Software Development & AI",
                "category": "technology",
                "duration": "6 Months",
                "fee": 450000,
                "description": "Master modern web development and AI-powered software engineering. Learn how to build professional applications from frontend to backend using industry-standard technologies.",
                "overview": "This intensive program takes students from beginner level to professional software developer. Students learn frontend development, backend development, databases, APIs, deployment, version control and practical AI integration.",
                "featured": True,
                "skills": ["HTML5", "CSS3", "JavaScript", "Bootstrap", "React", "Python", "Django", "REST APIs", "Git & GitHub", "AI Integration"],
                "outcomes": ["Frontend Developer", "Backend Developer", "Full-stack Developer", "Software Engineer", "AI Application Developer"],
                "requirements": ["No prior coding experience required", "Laptop Computer", "Willingness to learn"],
                "modules": ["HTML & CSS Fundamentals", "JavaScript Programming", "Bootstrap Library", "React Development", "Python Programming", "Django Backend Development", "Database Design", "REST API Development", "Authentication & Security", "AI Tools & Integration", "Deployment & DevOps Basics", "Capstone Project"],
            },
            {
                "slug": "data-science",
                "title": "Data Science with Python & R",
                "category": "technology",
                "duration": "5 Months",
                "fee": 450000,
                "description": "Learn data analysis, visualization, machine learning and predictive modeling using Python and R.",
                "overview": "Students learn how to collect, clean, analyze and visualize data to make informed business decisions.",
                "featured": True,
                "skills": ["Python", "R Programming", "Pandas", "NumPy", "SQL", "Data Visualization", "Machine Learning", "Statistics"],
                "outcomes": ["Data Analyst", "Data Scientist", "Business Intelligence Analyst", "Research Analyst"],
                "requirements": ["Basic computer knowledge", "Laptop Computer"],
                "modules": ["Python Fundamentals", "R Programming", "Statistics", "Data Cleaning", "Data Visualization", "Machine Learning", "Business Intelligence", "Final Data Project"],
            },
            {
                "slug": "ai-automation",
                "title": "AI Automation",
                "category": "technology",
                "duration": "2 Months",
                "fee": 250000,
                "description": "Learn how to automate business processes using modern AI tools and workflows.",
                "overview": "Students learn practical automation techniques that increase productivity and reduce repetitive work.",
                "featured": True,
                "skills": ["ChatGPT", "Workflow Automation", "Prompt Engineering", "No-Code Tools", "Business Automation"],
                "outcomes": ["AI Automation Specialist", "Productivity Consultant", "Business Automation Manager"],
                "requirements": ["Laptop Computer"],
                "modules": ["Introduction to AI", "Prompt Engineering", "Workflow Automation", "Business Automation", "Automation Projects"],
            },
            {
                "slug": "ai-engineering",
                "title": "Artificial Intelligence Engineering",
                "category": "technology",
                "duration": "4 Months",
                "fee": 450000,
                "description": "Build intelligent systems using machine learning, deep learning and modern AI technologies.",
                "overview": "Learn the engineering side of AI and create practical solutions using real-world datasets.",
                "featured": True,
                "skills": ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "LLMs"],
                "outcomes": ["AI Engineer", "Machine Learning Engineer", "AI Solutions Developer"],
                "requirements": ["Laptop Computer", "Basic programming knowledge preferred"],
                "modules": ["Python for AI", "Machine Learning", "Neural Networks", "Deep Learning", "Large Language Models", "AI Deployment"],
            },
            {
                "slug": "cyber-security",
                "title": "Cyber Security",
                "category": "technology",
                "duration": "5 Months",
                "fee": 450000,
                "description": "Protect systems, networks and organizations from cyber threats.",
                "overview": "Learn practical cyber security skills including penetration testing and network defense.",
                "featured": True,
                "skills": ["Ethical Hacking", "Network Security", "Risk Assessment", "Penetration Testing", "Digital Forensics"],
                "outcomes": ["Cyber Security Analyst", "Security Consultant", "Ethical Hacker", "SOC Analyst"],
                "requirements": ["Laptop Computer"],
                "modules": ["Networking Fundamentals", "Cyber Security Basics", "Ethical Hacking", "Network Defense", "Digital Forensics", "Security Auditing"],
            },
            {
                "slug": "business-growth",
                "title": "Business Startup & Growth to ₦50M",
                "category": "business",
                "duration": "6 Months",
                "fee": 450000,
                "description": "Learn how to start, manage and scale a profitable business from idea stage to sustainable growth.",
                "overview": "This program equips aspiring entrepreneurs and business owners with practical strategies for launching, managing and growing businesses.",
                "featured": True,
                "skills": ["Business Planning", "Marketing Strategy", "Sales & Negotiation", "Financial Management", "Business Operations", "Leadership"],
                "outcomes": ["Business Owner", "Startup Founder", "Business Consultant", "Operations Manager", "Entrepreneur"],
                "requirements": ["No prior business experience required", "Laptop Computer", "Passion for entrepreneurship"],
                "modules": ["Business Fundamentals", "Business Model Development", "Market Research", "Branding & Positioning", "Digital Marketing", "Sales & Customer Acquisition", "Financial Management", "Operations Management", "Business Scaling Strategies", "Leadership & Team Building", "Investment & Funding", "Business Growth Project"],
            },
            {
                "slug": "project-management",
                "title": "Project Management & Business Development",
                "category": "business",
                "duration": "2 Months",
                "fee": 250000,
                "description": "Develop the skills required to manage projects successfully and drive business growth.",
                "overview": "Students learn project planning, execution, monitoring and business development strategies that help organizations achieve their goals efficiently.",
                "featured": True,
                "skills": ["Project Planning", "Project Scheduling", "Risk Management", "Business Development", "Stakeholder Management", "Team Leadership", "Communication", "Proposal Writing"],
                "outcomes": ["Project Manager", "Business Development Officer", "Operations Coordinator", "Project Consultant", "Business Strategist"],
                "requirements": ["Basic computer knowledge", "Laptop Computer"],
                "modules": ["Introduction to Project Management", "Project Planning & Scheduling", "Project Execution", "Risk Management", "Business Development Fundamentals", "Proposal & Report Writing", "Team Leadership", "Client Relationship Management", "Monitoring & Evaluation", "Capstone Project"],
            },
            {
                "slug": "phone-repair",
                "title": "Computer & Mobile Phone Repair",
                "category": "vocational",
                "duration": "6 Months",
                "fee": 550000,
                "description": "Master the diagnosis, maintenance and repair of computers, smartphones and electronic devices.",
                "overview": "Students receive hands-on training in hardware troubleshooting, repairs, maintenance and customer service for technology devices.",
                "featured": True,
                "skills": ["Phone Repair", "Computer Repair", "Hardware Diagnostics", "Soldering Techniques", "Device Maintenance", "Software Installation", "Troubleshooting", "Customer Service"],
                "outcomes": ["Phone Repair Technician", "Computer Technician", "Workshop Owner", "Maintenance Specialist", "Technical Consultant"],
                "requirements": ["No prior experience required", "Interest in electronics"],
                "modules": ["Electronic Components", "Phone Hardware Repair", "Laptop Repair", "Desktop Repair", "Software Troubleshooting", "Device Diagnostics", "Soldering & Micro Repairs", "Customer Management", "Workshop Management", "Practical Industry Project"],
            },
            {
                "slug": "car-diagnosis",
                "title": "Car Diagnosis & Programming",
                "category": "vocational",
                "duration": "2 Months",
                "fee": 250000,
                "description": "Learn modern vehicle diagnostics, fault detection and ECU programming using industry tools.",
                "overview": "Students gain practical knowledge in identifying vehicle faults, interpreting diagnostic reports and programming automotive systems.",
                "featured": True,
                "skills": ["Vehicle Diagnostics", "ECU Programming", "Fault Detection", "Automotive Electronics", "Diagnostic Tools", "Vehicle Maintenance"],
                "outcomes": ["Diagnostic Technician", "Automotive Programmer", "Workshop Specialist", "Automobile Consultant"],
                "requirements": ["Interest in automobiles", "Basic technical knowledge is helpful"],
                "modules": ["Automotive Electronics", "Vehicle Computer Systems", "Diagnostic Equipment", "Fault Code Analysis", "ECU Programming", "Sensor Testing", "Vehicle Maintenance", "Practical Diagnostics"],
            },
            {
                "slug": "automobile-electricals",
                "title": "Automobile Rewire & Electricals",
                "category": "vocational",
                "duration": "6 Months",
                "fee": 450000,
                "description": "Become an expert in automotive electrical systems, rewiring and electrical fault repairs.",
                "overview": "Students learn how vehicle electrical systems work and gain hands-on experience diagnosing and repairing electrical faults.",
                "featured": True,
                "skills": ["Vehicle Rewiring", "Electrical Troubleshooting", "Battery Systems", "Alternator Repair", "Starter Systems", "Automotive Wiring", "Circuit Testing"],
                "outcomes": ["Automobile Electrician", "Electrical Technician", "Workshop Owner", "Maintenance Specialist", "Automotive Consultant"],
                "requirements": ["No prior experience required", "Interest in automobile systems"],
                "modules": ["Electrical Fundamentals", "Vehicle Wiring Systems", "Battery & Charging Systems", "Starter Systems", "Circuit Testing", "Electrical Fault Diagnosis", "Vehicle Rewiring", "Workshop Safety", "Practical Electrical Projects"],
            },
        ]

        for course_data in courses:
            course, created = Course.objects.get_or_create(
                slug=course_data['slug'],
                defaults=course_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created course: {course.title}'))
            else:
                self.stdout.write(self.style.WARNING(f'Already exists: {course.title}'))

        self.stdout.write(self.style.SUCCESS('Done seeding courses!'))