# Generated by Django 5.0.7 on 2026-09-30 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_guest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='guests.guest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
