# Generated by Django 5.0.7 on 2026-09-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_attachment_name_message_attachment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
