# Generated by Django 5.0.7 on 2026-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_conversationparticipant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('broadcast', 'Broadcast')], default='direct', max_length=10),
        ),
    ]
