# Generated by Django 5.0.7 on 2026-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_classsession_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='topic',
        ),
        migrations.AddField(
            model_name='classsession',
            name='topics_covered',
            field=models.TextField(blank=True, help_text='Topics covered in this session — one per line, or comma-separated'),
        ),
    ]
