# Generated by Django 5.0.7 on 2026-07-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_remove_classsession_topic_and_more'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='project_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='class_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cohort',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cohorts', to='tutors.tutor'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='topics_covered',
            field=models.TextField(blank=True),
        ),
    ]
