# Generated by Django 5.0.7 on 2026-08-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_classsession_project_note_cohort_class_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='lesson_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
