# Generated by Django 5.0.7 on 2026-08-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_classsession_ended_at_classsession_lesson_outcome_and_more'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('stage_1', 'Month 1'), ('stage_2', 'Month 2'), ('stage_3', 'Month 3')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='capstone_projects/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_projects', to='cohorts.cohort')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capstone_projects', to='tutors.tutor')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
