# Generated by Django 5.0.7 on 2026-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_classproject_studentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='project_type',
            field=models.CharField(choices=[('capstone', 'Capstone (End of Program)'), ('monthly', 'Monthly / Class Project')], default='capstone', max_length=20),
        ),
    ]
