# Generated by Django 5.0.7 on 2026-08-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0009_studentproject_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
