# Generated by Django 5.0.7 on 2026-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0011_classsession_end_latitude_classsession_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='content',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessed_on',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='student_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='tutor_observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
