# Generated by Django 5.0.7 on 2026-08-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_remove_assessment_content_assessment_assessed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessed_on',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student_answer',
            field=models.TextField(default=''),
        ),
    ]
