# Generated by Django 5.0.7 on 2026-09-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0013_alter_assessment_assessed_on_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('cohort', 'date')},
        ),
    ]
