# Generated by Django 5.0.7 on 2026-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0014_alter_classsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='class_times',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
